# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#

templates:
  params:
    author-name: nghialv
    author-email: nghialv2607@gmail.com
    category: learning
    copyright: "Copyright: (c) 2016 nghialv"
    github-username: nghialv

